import unittest
import os
from data_science.adk.tools import query_duckdb, python_repl

class TestTools(unittest.TestCase):
    def setUp(self):
        # Path to mock DB generated by e2e_runner
        self.db_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "data", "logistics_analytical.db"))
        # Ensure data directory exists for python_repl results
        os.makedirs(os.path.join(os.path.dirname(__file__), "..", "results"), exist_ok=True)

    def test_query_duckdb_success(self):
        if not os.path.exists(self.db_path):
             self.skipTest(f"Mock DB not found at {self.db_path}")
        
        # Query the shipping_events table which should exist
        query = "SELECT count(*) FROM shipping_events"
        result = query_duckdb(query)
        self.assertIn("count(*)", result)
        self.assertTrue(len(result) > 0)

    def test_query_postgresql_simulated(self):
        from data_science.adk.tools import query_postgresql
        query = "SELECT table_name FROM information_schema.tables"
        result = query_postgresql(query)
        self.assertIn("users", result)
        self.assertIn("orders", result)
        self.assertIn("products", result)
        self.assertIn("order_details", result)

    def test_query_postgresql_products(self):
        from data_science.adk.tools import query_postgresql
        query = "SELECT * FROM products WHERE category = 'Electronics'"
        result = query_postgresql(query)
        self.assertIn("SuperWidget", result)
        self.assertIn("MegaGizmo", result)
        self.assertIn("HyperPad", result)

    def test_python_repl_success(self):
        code = "a = 5\nb = 10\nprint(a + b)"
        result = python_repl(code)
        self.assertIn("15", result)

    def test_python_repl_plot(self):
        code = """
import matplotlib.pyplot as plt
import os
plt.figure()
plt.plot([1, 2, 3], [4, 5, 2])
plt.title("Test Plot")
# Save to results dir
results_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "results"))
plt.savefig(os.path.join(results_dir, "test_plot.png"))
plt.close()
"""
        result = python_repl(code)
        # Check if plot was saved
        plot_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "results", "test_plot.png"))
        self.assertTrue(os.path.exists(plot_path))
        if os.path.exists(plot_path):
             os.remove(plot_path) # Clean up

if __name__ == "__main__":
    unittest.main()
