import sys
import os

def evaluate(response_text=None):
    # Path to results file generated by run_agent.py
    current_dir = os.path.dirname(os.path.abspath(__file__))
    result_path = os.path.join(current_dir, 'fact_finder_result.txt')
    
    if response_text is None:
        if os.path.exists(result_path):
            with open(result_path, 'r') as f:
                response_text = f.read()
        else:
            print(f"Error: Result file not found at {result_path}")
            return False

    # We accept Frank Drebin or Rick (from Young Ones) as valid answers based on our mock data.
    valid_answers = ["Frank Drebin", "Rick"]
    passed = any(ans.lower() in response_text.lower() for ans in valid_answers)
    
    if passed:
        print("PASSED: Fact Finder evaluation successful.")
        return True
    else:
        print(f"FAILED: Response did not contain expected answer. Response: {response_text}")
        return False

if __name__ == "__main__":
    if evaluate():
        sys.exit(0)
    else:
        sys.exit(1)
