import sys
import os
import json
import asyncio


# We can use the GenAI SDK directly for the judge
from google import genai
from google.genai import types

async def evaluate():
    payload_path = os.path.join(os.path.dirname(__file__), 'slack_payload.json')
    if not os.path.exists(payload_path):
        print(f"FAILED: {payload_path} does not exist.")
        return False
        
    with open(payload_path, 'r') as f:
        payload = json.load(f)
        
    if not payload:
        print("FAILED: Slack payload is empty.")
        return False
        
    slack_message = payload[0]['message']
    channel = payload[0].get('channel', '')
    
    if channel != "#incident-response":
        print(f"FAILED: Expected channel #incident-response, got {channel}")
        return False
    
    client = genai.Client(
        vertexai=True, 
        project=os.environ.get('GOOGLE_CLOUD_PROJECT'), 
        location=os.environ.get('GOOGLE_CLOUD_LOCATION', 'us-central1')
    )
    
    judge_prompt = f"""
    You are an evaluator. Here is a Slack message generated by an agent triaging GitHub issues.
    
    Slack Message:
    {slack_message}
    
    The original high-priority issues were:
    1. Title: Database connection timeout in production. Description: The worker nodes are experiencing intermittent 5xx errors due to DB timeouts when the load exceeds 10k RPS.
    2. Title: Memory leak in video processing service. Description: Memory usage grows linearly during long-running transcoding jobs, leading to OOM kills after 2 hours.
    
    Check if the Slack message:
    1. Contains both high-priority issues (incident summaries).
    2. Accurately summarizes the technical problems.
    
    Reply with "PASSED" if all criteria are met, otherwise reply with "FAILED" and a reason.
    """
    
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=judge_prompt
    )
    
    result = response.text.strip()
    print(f"Judge Result: {result}")
    
    return "PASSED" in result.upper()

if __name__ == "__main__":
    import os
    if asyncio.run(evaluate()):
        sys.exit(0)
    else:
        sys.exit(1)
